### ISSUE TITLE
2.0.5-Population Ancestry Inference 

### ISSUE THREAD

**Issue by chadisaad** [mkveerapen/covid19_sequencing#3]
Hello humar,

Any news for the 2.0.5-Population Ancestry Inference part ? Code suggestion ?

Thank you !

https://github.com/mkveerapen/covid19_sequencing/blob/master/Hail_COVID19weswgs.ipynb?short_path=df36329#L870

**Comment by mkveerapen** [comment]
Hi, Chadi! Sorry for the delay. It truly slipped my periphery. It may not be updated till mid November since we are in conference season now! Thank you for the reminder :)
